### ISSUE TITLE
V1.0.5 only operating on image height

### ISSUE THREAD

**Issue by craigs100** [Vrijdagonline/VrijdagOnline.ImageResizer#1]
Umb V11.2.2 ImageResizer  V1.0.5

Appears only to operate on image height.  

With the appsettings set as shown below, uploading an image of 2500 x 888 results in an image size of 2162 x 768. It should of course have been 1024 x 427

  "ImageResizer": {
    "ImageResizeDisabled": false,
    "ImageResizeWidth": 1024,
    "ImageResizeHeight": 768,
    "ImageResizeSuffix": "_resized",
    "ImageResizeKeepOriginal": false,
    "ImageResizeUpscale": false,
    "ImageResizePreviewWidth": 240,
    "ImageResizePreviewHeight": 136,
    "ImageResizePreviewSuffix": "_preview",
    "ImageResizeKeepPreview": false,
    "ImageResizeMaintainRatio": true,
    "ImageResizeApplyToExistingImages": true
  }

**Comment by Momkay** [comment]
Will look into it asap!

**Comment by Momkay** [comment]
@craigs100 We've fixed the issue in 1.1.0, thank you for your patience.
